kind: pipeline
name: default

steps:
  - name: compile
    image: gradle:jdk10
    commands:
      - gradle clean
      - gradle build
    when:
      branch:
        - master
      event:
        - push
        - pull_request
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
    - promote
    - rollback